import './assets/main.css'

import { createApp } from 'vue'

import App from './App.vue'
import router from './router'

// Font Awesome setup
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import specific icons
import {
  faUser,
  faBell,
  faPlus,
  faTachometerAlt,
  faAmbulance,
  faExclamationTriangle,
  faFileAlt,
  faChartBar,
  faEdit,
  faEye,
  faCog,
  faPhone,
  faPeopleGroup,
  faMapLocation,
  faHeadset,
  faDriversLicense,
  faMedkit,
  faFilePdf,
  faFileExcel,
  faTrashAlt,
  faHistory,
  faUserGroup,
  faUserShield,
  faShieldAlt,
  faMobileAndroidAlt,
  faRemove,
  faHeart,
  faVial,
  faInfoCircle,
  faPaperPlane,
  faRulerCombined,
  faQuestion,
  faSms,
  faBan,
  faXmark,
  faCheckCircle,
  faCheck,
  faFilter,
  faCrown,
  faUsers,
  faChartLine,
  faFloppyDisk,
  faDownload,
  faTrash,
  faRightFromBracket,
  faClock,
  faFileCsv,
  faFire,
  faKitMedical,
  faListAlt,
  faSearch,
  faDatabase,
  faHourglass2,
  faCheckDouble,
  faFlagCheckered,
  faChevronDown,
} from '@fortawesome/free-solid-svg-icons'

// Add to library
library.add(
  faUser,
  faBell,
  faPlus,
  faTachometerAlt,
  faAmbulance,
  faExclamationTriangle,
  faFileAlt,
  faChartBar,
  faEdit,
  faEye,
  faCog,
  faPhone,
  faPeopleGroup,
  faMapLocation,
  faHeadset,
  faDriversLicense,
  faMedkit,
  faFilePdf,
  faFileExcel,
  faTrashAlt,
  faHistory,
  faUserGroup,
  faUserShield,
  faShieldAlt,
  faMobileAndroidAlt,
  faRemove,
  faHeart,
  faVial,
  faInfoCircle,
  faPaperPlane,
  faRulerCombined,
  faQuestion,
  faSms,
  faBan,
  faXmark,
  faCheckCircle,
  faCheck,
  faFilter,
  faCrown,
  faUsers,
  faChartLine,
  faFloppyDisk,
  faDownload,
  faTrash,
  faRightFromBracket,
  faClock,
  faFileCsv,
  faFire,
  faKitMedical,
  faListAlt,
  faSearch,
  faDatabase,
  faCheckCircle,
  faHourglass2,
  faFlagCheckered,
  faChevronDown,
)

const app = createApp(App)
app.component('font-awesome-icon', FontAwesomeIcon)
app.use(router)
app.mount('#app')
